Tests that pause on promise rejection works.

=== Pausing only on uncaught exceptions ===
Set timer for test function.
Call stack:
    0) testFunction (async-pause-on-exception.js:41)
    [setTimeout]
    0) scheduleTestFunction <omitted>
    <... skipped remaining frames ...>
Paused on promise rejectionError: uncaught

=== Pausing on all exceptions ===
Set timer for test function.
Call stack:
    0) testFunction (async-pause-on-exception.js:40)
    [setTimeout]
    0) scheduleTestFunction <omitted>
    <... skipped remaining frames ...>
Paused on promise rejectionError: caught
Call stack:
    0) testFunction (async-pause-on-exception.js:41)
    [setTimeout]
    0) scheduleTestFunction <omitted>
    <... skipped remaining frames ...>
Paused on promise rejectionError: uncaught

