This is a testharness.js-based test.
[FAIL] Cancel promise is created in same global as stream
  assert_equals: Cancel promise comes from the same global as the stream expected true but got false
Harness: the test ran to completion.

